---
title: trumpet
timezone: Europe/Berlin
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
remote_theme: chromatical/jekyll-materialdocs
copyright: gofunky
mdl_colors: blue_grey-orange
search: false
